---
name: evcc (Proxy)
version: 1.0.0
slug: evcc_proxy
description: Home Assistant add-on that provides Ingress access to an externally hosted evcc instance via a lightweight reverse proxy (does not run evcc itself)
url: https://github.com/pvillmann/hassio-addon-evcc-proxy
arch:
  - armv7
  - aarch64
  - amd64
startup: application
panel_icon: mdi:ev-station
panel_admin: false
boot: auto
ingress: true
ingress_stream: true
ingress_port: 8099
init: true
timeout: 30
watchdog: http://[HOST]:[PORT:8099]
options:
  evcc-url: http://evcc.local:7070
schema:
  evcc-url: str
